account_id = "e930788f02492016821540a9f74829d2"
name = "social-media-platform"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-10-18"
